alias ls='ls -F'
alias ll='ls -al'
# alias gh='history|grep' # conflict with github cli
alias count='find . -type f | wc -l'

alias cl='clear'
alias d='cd_ls'

alias k8up='cd ~/proj/k8s/jmy-k8s && vagrant up'
alias g=gcloud
alias gssh='gcloud compute ssh'
alias gconf='gcloud config configurations'
alias gke='gcloud container clusters'
alias gs=gsutil

alias p3='/usr/local/bin/python3'

#alias config='/usr/bin/git --git-dir=/Users/ldong/.cfg/ --work-tree=/Users/ldong'
alias gm='git add --all && git commit -am'
alias gb='git branch'
alias gc='git checkout'
alias gst='git status'
alias gp='git push'
alias gpnew='git push --set-upstream origin'
alias gcf='git config'
alias tf='terraform'
alias tfi='terraform init'
alias tfp='terraform plan'
alias tfip='terraform init && terraform plan'
alias tfap='terraform apply'

# Feature: cd a folder ad list files
# Usage cl Downloads
# Refer: https://opensource.com/article/19/7/bash-aliases

function cd_ls () {
    DIR="$*";
    # if no DIR given, go home
    if [ $# -lt 1 ]; then
                DIR=$HOME;
    fi;
    builtin cd "${DIR}" && \
    # use your preferred ls command
        ls -F --color=auto
}
