# Moved all aliases to bash_aliases

# Usage: 
# source $HOME/.bashrc
# source $HOME/.zshrc



# Dot files for Bash

[ -f $HOME/.bash_functions ] && source $HOME/.bash_functions

if [ -e $HOME/.bash_aliases ]; then
    source $HOME/.bash_aliases
fi

[ -f $HOME/.bash_docker_aliases ] && source $HOME/.bash_docker_aliases
[ -f $HOME/.bash_kubectl_aliases ] && source $HOME/.bash_kubectl_aliases


# Dot files for zsh

[ -f $HOME/.bashrc_functions ] && source $HOME/.bashrc_functions

if [ -e $HOME/.bashrc_aliases ]; then
    source $HOME/.bashrc_aliases
fi

[ -f $HOME/.bashrc_docker_aliases ] && source $HOME/.bashrc_docker_aliases
[ -f $HOME/.bashrc_kubectl_aliases ] && source $HOME/.bashrc_kubectl_aliases


export g=gcloud
export glog='gcloud auth login'
export gloga='gcloud auth application-default login'
export CLOUDSDK_PYTHON=python3 

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jimmy.cui/Documents/my-apps/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/jimmy.cui/Documents/my-apps/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
# if [ -f '/Users/jimmy.cui/Documents/my-apps/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/jimmy.cui/Documents/my-apps/google-cloud-sdk/completion.zsh.inc'; fi



export PATH="/opt/homebrew/bin:$PATH"

# sudo chown -R jimmy.cui /opt/homebrew 
# sudo chown -R jimmy.cui /tmp



 

