# Moved all aliases to bash_aliases

# Usage: 
# source $HOME/.bashrc
# source $HOME/.bashrc/.zshrc

# Dot files for Bash


export PATH=$HOME/kubectx:$PATH

[ -f $HOME/.bash_functions ] && source $HOME/.bash_functions

if [ -e $HOME/.bash_aliases ]; then
    source $HOME/.bash_aliases
fi

[ -f $HOME/.bash_docker_aliases ] && source $HOME/.bash_docker_aliases
[ -f $HOME/.bash_kubectl_aliases ] && source $HOME/.bash_kubectl_aliases


# Dot files for zsh

[ -f $HOME/.bashrc_functions ] && source $HOME/.bashrc_functions

if [ -e $HOME/.bashrc_aliases ]; then
    source $HOME/.bashrc_aliases
fi

[ -f $HOME/.bashrc_docker_aliases ] && source $HOME/.bashrc_docker_aliases
[ -f $HOME/.bashrc_kubectl_aliases ] && source $HOME/.bashrc_kubectl_aliases


# Resolve python3.9 issue with error: AttributeError: module 'importlib' has no attribute 'util'
# solution: user python 3.8 

# make sure python3 uses 3.8
# which python3
# should be /usr/bin/python3

# remove the incorerct soft link of 3.9
# rm /usr/local/bin/python3

export CLOUDSDK_PYTHON=python3 
