# Moved all aliases to bash_aliases

# Usage: 
# source $HOME/.bashrc
# source $HOME/.zshrc

# Dot files for zsh


export g=gcloud
export glog='gcloud auth login'
export gloga='gcloud auth application-default login'
# export CLOUDSDK_PYTHON=python3 

[ -f $HOME/.bash_functions ] && source $HOME/.bash_functions

if [ -e $HOME/.bash_aliases ]; then
    source $HOME/.bash_aliases
fi

[ -f $HOME/.bash_docker_aliases ] && source $HOME/.bash_docker_aliases
[ -f $HOME/.bash_kubectl_aliases ] && source $HOME/.bash_kubectl_aliases


[ -f $HOME/.bashrc_functions ] && source $HOME/.bashrc_functions

if [ -e $HOME/.bashrc_aliases ]; then
    source $HOME/.bashrc_aliases
fi

[ -f $HOME/.bashrc_docker_aliases ] && source $HOME/.bashrc_docker_aliases
[ -f $HOME/.bashrc_kubectl_aliases ] && source $HOME/.bashrc_kubectl_aliases


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jimmy.cui/Documents/my-apps/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/jimmy.cui/Documents/my-apps/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
# if [ -f '/Users/jimmy.cui/Documents/my-apps/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/jimmy.cui/Documents/my-apps/google-cloud-sdk/completion.zsh.inc'; fi



export PATH="/opt/homebrew/bin:$PATH"

# sudo chown -R jimmy.cui /opt/homebrew 
# sudo chown -R jimmy.cui /tmp

## To start colima now and restart at login:
# brew services start colima

# Or, if you don't want/need a background service you can just run:
#  /opt/homebrew/opt/colima/bin/colima start -f
export DOCKER_HOST="unix://${HOME}/.colima/default/docker.sock"
